
	const_def

	const SPECIAL_MAP       ; 00
	const NEW_BARK_TOWN     ; 01
	const ROUTE_29          ; 02
	const CHERRYGROVE_CITY  ; 03
	const ROUTE_30          ; 04
	const UNION_CAVE        ; 0a
	const ROUTE_31          ; 05
	const VIOLET_CITY       ; 06
	const ROUTE_36          ; 14
	const ROUTE_34          ; 0f
	const ILEX_FOREST       ; 0e
	const ROUTE_32          ; 08
	const ECRUTEAK_CITY     ; 16
	const ROUTE_42          ; 22
	const MT_MORTAR         ; 23
	const MAHOGANY_TOWN     ; 24
	const ROUTE_35          ; 12
	const GOLDENROD_CITY    ; 10
	const RADIO_TOWER       ; 11
	const ROUTE_44          ; 2b
	const OLIVINE_CITY      ; 1b
	const ROUTE_39          ; 1a
	const NATIONAL_PARK     ; 13
	const ROUTE_38          ; 19
	const AZALEA_TOWN       ; 0c
	const ROUTE_37          ; 15
	const LAKE_OF_RAGE      ; 26
	const ROUTE_40          ; 1e
	const ROUTE_41          ; 1e
	const CIANWOOD_CITY     ; 21
	const ROUTE_43          ; 25
	const ICE_PATH          ; 28
	const ROUTE_33          ; 0b
	const BLACKTHORN_CITY   ; 29
	const ROUTE_45          ; 27
	const ROUTE_46          ; 2d
	const ROUTE_27          ; 5c
	const ROUTE_26          ; 5b
	const VICTORY_ROAD      ; 58
	const ROUTE_23          ; 59
	const INDIGO_PLATEAU    ; 5a

KANTO_LANDMARK EQU const_value

	const PALLET_TOWN       ; 2f
	const ROUTE_7           ; 3f
	const LAVENDER_TOWN     ; 45
	const ROUTE_1           ; 32
	const ROUTE_6           ; 36
	const VIRIDIAN_CITY     ; 31 
	const ROUTE_3           ; 34
	const MT_MOON           ; 35
	const ROUTE_5           ; 3a
	const PEWTER_CITY       ; 33
	const ROUTE_25          ; 39
	const ROUTE_14          ; 4c
	const ROCK_TUNNEL       ; 42
	const SAFFRON_CITY      ; 48
	const ROUTE_9           ; 41
	const ROUTE_8           ; 40
	const ROUTE_11          ; 49
	const FUCHSIA_CITY      ; 51
	const ROUTE_4           ; 3c
	const CELADON_CITY      ; 47
	const ROUTE_15          ; 4d
	const DIGLETTS_CAVE     ; 3e
	const ROUTE_13          ; 4b
	const ROUTE_18          ; 4a
	const CERULEAN_CITY     ; 37
	const ROUTE_12          ; 50
	const VERMILION_CITY    ; 3d
	const SILVER_CAVE       ; 2e
	const UNDERGROUND       ; 3b
	const FAST_SHIP         ; 5f
